import 'package:floor/floor.dart';

//Here, we are saying to floor that this is a class that defines an entity
@entity
class Todo {
  //id will be the primary key of the table. Moreover, it will be autogenerated.
  //id is nullable since it is autogenerated.
  @PrimaryKey(autoGenerate: true)
  //Vil egt at Primary key skal være student ID
  final String username; 

  //For the sake of simplicity, a Todo has only a name.
  final String password;
  final int? height;
  final int? age;
  final int? weight;
  final String? gender;

  //Default constructor
  Todo(this.username, this.password, this.height, this.age, this.weight, this.gender);
  
}//Todo 