name: agri_fit
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.1.0
  http: ^0.13.6
  floor: ^1.4.2

  google_nav_bar: ^5.0.6
  fl_chart: ^0.63.0
  url_launcher: ^6.1.11

  jwt_decoder: ^2.0.1
  intl: ^0.18.1
  flutter_login: ^4.1.1
  cupertino_icons: ^1.0.2

  dio: ^5.0.0
  provider: ^6.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  floor_generator: ^1.4.2
  build_runner: ^2.1.2

flutter:
  uses-material-design: true

  assets:
    - assets/map_image.jpg
    - assets/logos/ali.png
    - assets/logos/conad.png
    - assets/logos/eurospin.png
    - assets/logos/iperrosetto.png
    - assets/logos/lidl.png
    - assets/logos/pam.png
    - assets/logos/spar.jpeg